---
- name: Reload systemd
  become: false
  remote_user: media
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Restart sr-radio-api
  become: false
  remote_user: media
  ansible.builtin.systemd:
    name: sr-radio-api
    state: restarted
    scope: user
  when: not ansible_check_mode
