---
- name: Reload systemd
  become: false
  remote_user: media
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Restart bluetooth
  ansible.builtin.systemd:
    name: bluetooth
    state: restarted
    scope: system

- name: Restart wireplumber
  become: false
  remote_user: media
  ansible.builtin.systemd:
    name: wireplumber
    state: restarted
    scope: user