wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
}

monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink ]
  bluez5.codecs = [ sbc sbc_xq aac ]
  bluez5.enable-sbc-xq = true
  bluez5.enable-hw-volume = true
}
