#!/usr/bin/env python3
"""Enable Bluetooth pairing mode for 3 minutes."""
import dbus

bus = dbus.SystemBus()
adapter = dbus.Interface(
    bus.get_object('org.bluez', '/org/bluez/hci0'),
    'org.freedesktop.DBus.Properties'
)
adapter.Set('org.bluez.Adapter1', 'DiscoverableTimeout', dbus.UInt32(180))
adapter.Set('org.bluez.Adapter1', 'PairableTimeout', dbus.UInt32(180))
adapter.Set('org.bluez.Adapter1', 'Discoverable', True)
adapter.Set('org.bluez.Adapter1', 'Pairable', True)
print("Bluetooth pairing mode active for 3 minutes.")
